version: 2
updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
      target-branch: "main"

    # Maintain dependencies for npm
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "monthly"
      target-branch: "main"

    # Maintain dependencies for pip
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "monthly"
      target-branch: "main"
