name: Python Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  checks:
    runs-on: ubuntu-latest
    if: "${{!contains(github.event.head_commit.message, 'ci skip')}}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          python -m pip install pip wheel pipx --upgrade
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Cache Pre-Commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit

      - name: Install Python Dependencies
        run: poetry install --sync --all-extras

      - name: Generate Code
        run: poetry run python build.py

      - name: Run Pre-Commit Checks
        run: poetry run pre-commit run --all-files --color=always --show-diff-on-failure